import { ThemeProvider } from "@/components/ui/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
// if (typeof window === "undefined") {
//   cron.schedule("*/2 * * * *", async () => {
//     console.log("Running escalation job...");
//     try {
//       await axios.post("http://localhost:3000/api/escalate-tickets");
//       console.log("Escalation job completed successfully.");
//     } catch (error) {
//       console.error("Escalation job failed:", error);
//     }
//   });
// }
// Runs every hour
// if (typeof window === "undefined") {
//     cron.schedule("*/1 * * * *", async () => {
//       console.log("⏳ Running SLA Monitoring Cron Job...");      try {
//         // await axios.post("http://localhost:3000/api/monitor-sla");
//         await monitorSLA()
//         console.log("✅ SLA Monitoring Service Started...");

//         // console.log("sla monitor job completed successfully.");
//       } catch (error) {
//         console.error("job failed:", error);  
//       }
//     });
//   }

const latoFont = Lato({
  subsets: ["latin"],
  weight: ['700', '900'],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Warranty Management System",
  description: "Generated by create next app",
  // icon for the app
  icons: {
    icon: '/logo.svg',
    shortcut: '/logo.svg',
    apple: '/logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="en">
      
      <body
        className={`${latoFont.className} ${latoFont.className} antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
        {children}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}


